import XCTest

final class GymBlockFlowTests: XCTestCase {
  var app: XCUIApplication!
  override func setUpWithError() throws {
    continueAfterFailure = false
    app = XCUIApplication()
    app.launchArguments = ["--ui-reset", "--demo"]
    app.launch()
  }
  private func tap(_ id: String) {
    let element = app.buttons[id].firstMatch
    XCTAssertTrue(element.waitForExistence(timeout: 6), id)
    for _ in 0..<4 {
      if element.isHittable { break }
      app.swipeUp()
    }
    XCTAssertTrue(element.isHittable, id)
    XCTAssertTrue(element.isEnabled, id)
    element.tap()
  }
  private func fill(_ id: String, _ value: String) {
    let field = app.textFields[id]
    XCTAssertTrue(field.waitForExistence(timeout: 6), id)
    for _ in 0..<3 {
      if field.isHittable { break }
      app.swipeUp()
    }
    field.tap()
    if let old = field.value as? String, old != field.placeholderValue {
      field.typeText(String(repeating: XCUIKeyboardKey.delete.rawValue, count: old.count))
    }
    field.typeText(value)

  }
  private func search(_ text: String) {
    let field = app.searchFields.firstMatch
    XCTAssertTrue(field.waitForExistence(timeout: 6))
    field.tap()
    field.typeText(text)
  }
  private func snap(_ name: String) {
    let shot = XCTAttachment(screenshot: app.screenshot())
    shot.name = name
    shot.lifetime = .keepAlways
    add(shot)
  }
  private func end() {
    tap("session.options")
    tap("session.finish")
  }
  private func editWeight(_ value: String) {
    tap("set.weight")
    fill("set.weight.manual", value)
    tap("set.weight.picker.done")
  }
  func testFreestyleSetCorrectionSwitchAndRelaunch() {
    XCTAssertTrue(app.buttons["home.start"].waitForExistence(timeout: 5))
    snap("redesign-01-home")
    tap("home.start")
    search("dum")
    snap("redesign-02-search")
    tap("exercise.curl")
    snap("redesign-03-ready")
    tap("set.weight")
    app.pickerWheels.firstMatch.adjust(toPickerWheelValue: "22.5")
    XCTAssertEqual(app.textFields["set.weight.manual"].value as? String, "22.5")
    snap("redesign-04-picker")
    fill("set.weight.manual", "25")
    XCTAssertEqual(app.textFields["set.weight.manual"].value as? String, "25")
    tap("set.weight.picker.done")
    tap("set.start")
    tap("set.reps.plus")
    tap("set.reps.plus")
    snap("redesign-05-active")
    fill("set.reps", "12")
    tap("set.stop")
    XCTAssertTrue(app.staticTexts["rest.elapsed"].exists)
    snap("redesign-06-rest")
    tap("set.saved")
    fill("edit.reps", "7")
    tap("edit.save")
    XCTAssertTrue(app.buttons["set.saved"].label.contains("7"))
    tap("set.start")
    fill("set.reps", "8")
    app.terminate()
    app.launchArguments = []
    app.launch()
    XCTAssertTrue(app.buttons["set.stop"].waitForExistence(timeout: 5))
    XCTAssertEqual(app.textFields["set.reps"].value as? String, "8")
    tap("session.options")
    tap("session.sets")
    tap("records.add")
    fill("edit.reps", "6")
    app.switches["Warm-up"].tap()
    snap("redesign-23-set-correction")
    tap("edit.save")
    tap("records.done")
    XCTAssertTrue(app.buttons["set.stop"].exists)
    XCTAssertEqual(app.textFields["set.reps"].value as? String, "8")
    tap("set.stop")
    tap("set.change")
    search("hammer")
    tap("exercise.hammer")
    XCTAssertTrue(app.staticTexts["rest.elapsed"].exists)
    editWeight("15")
    tap("set.start")
    tap("session.options")
    tap("set.attempt")
    XCTAssertTrue(app.buttons["set.saved"].label.contains("Attempt"))
    end()
    snap("redesign-07-summary")
    tap("summary.done")
    XCTAssertTrue(app.buttons["home.start"].exists)
  }
  func testSplitStartsDirectlyAndProgressShowsBeforeAfter() {
    tap("home.workout")
    app.buttons["Arms"].tap()
    tap("home.start")
    XCTAssertTrue(app.buttons["set.start"].exists)
    XCTAssertFalse(app.searchFields.firstMatch.exists)
    tap("set.start")
    fill("set.reps", "10")
    tap("set.stop")
    tap("set.change")
    tap("exercise.hammer")
    expectExercise("hammer")
    end()
    tap("summary.done")
    app.tabBars.buttons["History"].tap()
    app.segmentedControls["history.mode"].buttons["Progress"].tap()
    tap("progress.exercise.curl")
    XCTAssertTrue(app.staticTexts["progress.change"].waitForExistence(timeout: 5))
    snap("redesign-08-progress")
    tap("progress.chart")
    XCTAssertTrue(app.staticTexts["History"].exists)
  }
  func testPersonalOnboardingCalculationAndResume() {
    app.terminate()
    app.launchArguments = ["--ui-reset"]
    app.launch()
    snap("redesign-09-welcome")
    fill("name.field", "Sirish")
    tap("onboarding.continue")
    tap("distraction.Social feeds")
    snap("redesign-10-distractions")
    tap("onboarding.continue")
    tap("baseline.duration.60")
    tap("baseline.visits.3")
    snap("redesign-11-time")
    tap("onboarding.continue")
    tap("baseline.exercises.6")
    tap("baseline.sets.3")
    fill("baseline.reps", "10")
    snap("redesign-12-routine")
    app.terminate()
    app.launchArguments = []
    app.launch()
    XCTAssertTrue(app.textFields["baseline.reps"].waitForExistence(timeout: 5))
    XCTAssertEqual(app.textFields["baseline.reps"].value as? String, "10")
    tap("onboarding.continue")
    tap("baseline.scrolling.10")
    tap("onboarding.continue")
    XCTAssertTrue(app.staticTexts["30 min/week on feeds"].exists)
    tap("baseline.goalmenu")
    tap("baseline.customgoal")
    fill("baseline.goal", "7")
    tap("baseline.goal.save")
    XCTAssertTrue(app.buttons["baseline.goalmenu"].label.contains("7"))
    snap("redesign-13-personal-result")
    tap("onboarding.continue")
    XCTAssertTrue(
      app.staticTexts["This demo previews focus mode. It doesn't block other apps."].exists)
    snap("redesign-14-focus")
    tap("onboarding.continue")
    XCTAssertTrue(app.buttons["home.start"].waitForExistence(timeout: 5))
  }
  func testZeroScrollingSkipDurationAndEarlyEnd() {
    app.terminate()
    app.launchArguments = ["--ui-reset"]
    app.launch()
    tap("onboarding.continue")
    tap("distraction.None")
    tap("onboarding.continue")
    tap("onboarding.continue")
    tap("onboarding.continue")
    XCTAssertTrue(app.staticTexts["Keep your workout simple."].exists)
    XCTAssertFalse(app.staticTexts["min/week on feeds"].exists)
    tap("onboarding.skip")
    tap("home.start")
    search("Running")
    tap("exercise.run")
    tap("set.start")
    fill("set.minutes", "5")
    tap("set.stop")
    XCTAssertTrue(app.buttons["set.saved"].label.contains("5 min"))
    end()
    tap("summary.done")
    tap("home.start")
    tap("exercise.curl")
    XCTAssertFalse(app.buttons["set.start"].isEnabled)
    snap("redesign-24-first-weight")
    editWeight("10")
    tap("set.start")
    fill("set.reps", "8")
    end()
    tap("session.discardEnd")
    tap("summary.done")
    XCTAssertTrue(app.buttons["home.start"].exists)
  }
  func testNativeSplitEditorAndPoundsConversion() {
    tap("home.preferences")
    tap("settings.splits")
    tap("split.add")
    fill("split.name", "Monday")
    tap("split.exercises")
    tap("split.exercise.curl")
    tap("split.exercise.hammer")
    tap("split.exercises.done")
    tap("split.save")
    XCTAssertTrue(app.buttons["split.edit.Monday"].exists)
    snap("redesign-15-splits")
    tap("preferences.done")
    tap("home.workout")
    app.buttons["Monday"].tap()
    tap("home.start")
    tap("set.weight")
    fill("set.weight.manual", "10")
    XCTAssertEqual(app.textFields["set.weight.manual"].value as? String, "10")
    tap("set.weight.picker.done")
    tap("set.weight")
    app.segmentedControls.buttons["lb"].tap()
    XCTAssertEqual(app.textFields["set.weight.manual"].value as? String, "22.05")
    tap("set.weight.picker.done")
    tap("set.start")
    XCTAssertTrue(app.staticTexts["22.05 lb"].exists)
    tap("set.stop")
    tap("set.saved")
    tap("edit.delete")
    XCTAssertTrue(app.buttons["set.undo"].exists)
    tap("set.undo")
    XCTAssertTrue(app.staticTexts["rest.elapsed"].exists)
  }
  func testSpanishOnboardingAndBackPreserveAnswers() {
    app.terminate()
    app.launchArguments = ["--ui-reset"]
    app.launch()
    tap("onboarding.language")
    app.buttons["Español"].tap()
    XCTAssertTrue(app.staticTexts["Tu entrenamiento merece tu atención."].exists)
    snap("redesign-16-spanish")
    tap("onboarding.continue")
    tap("distraction.None")
    tap("onboarding.continue")
    tap("baseline.duration.60")
    tap("onboarding.continue")
    tap("onboarding.continue")
    tap("onboarding.back")
    XCTAssertTrue(app.textFields["baseline.exercises"].exists)
    tap("onboarding.back")
    XCTAssertEqual(app.textFields["baseline.duration"].value as? String, "60")
    tap("onboarding.skip")
    XCTAssertTrue(app.buttons["home.start"].waitForExistence(timeout: 5))
  }
  func testLargeTextWorkoutControlsStayReachable() {
    XCTAssertTrue(app.buttons["home.start"].waitForExistence(timeout: 5))
    snap("redesign-17-accessible-home")
    XCTAssertTrue(app.tabBars.buttons["History"].isHittable)
    tab("History")
    snap("gym-flow-12-accessible-history")
    tab("Home")
    tap("home.workout")
    app.buttons["Arms"].tap()
    tap("home.start")
    XCTAssertTrue(app.buttons["set.start"].isHittable)
    snap("redesign-18-accessible-ready")
    tap("set.weight")
    fill("set.weight.manual", "25")
    snap("redesign-25-accessible-weight-entry")
    tap("set.weight.picker.done")
    tap("set.start")
    XCTAssertTrue(app.buttons["set.stop"].isHittable)
    XCTAssertTrue(app.buttons["set.change"].isHittable)
    snap("redesign-19-accessible-active")
    tap("set.stop")
    XCTAssertTrue(app.buttons["set.start"].isHittable)
    XCTAssertTrue(app.buttons["set.change"].isHittable)
    snap("redesign-20-accessible-rest")
    app.terminate()
    app.launchArguments = ["--ui-reset"]
    app.launch()
    snap("redesign-21-accessible-welcome")
    tap("onboarding.continue")
    tap("distraction.None")
    tap("onboarding.continue")
    tap("baseline.duration.60")
    tap("onboarding.continue")
    snap("redesign-22-accessible-routine")
    tap("onboarding.skip")
    XCTAssertTrue(app.buttons["home.start"].waitForExistence(timeout: 5))
  }

  private func tab(_ name: String) {
    let button = app.tabBars.buttons[name]
    XCTAssertTrue(button.waitForExistence(timeout: 5))
    button.tap()
  }
  private func expectExercise(_ name: String) {
    let changed = expectation(
      for: NSPredicate(format: "label CONTAINS %@", name),
      evaluatedWith: app.buttons["set.exercise"])
    wait(for: [changed], timeout: 5)
  }
  private func elapsed() -> Int {
    let label = app.staticTexts["rest.elapsed"].label
    let parts = label.split(separator: ":").compactMap { Int($0) }
    return parts.count == 2 ? parts[0] * 60 + parts[1] : -1
  }
  func testGymNavigationAndChangingMindDuringSet() {
    XCTAssertFalse(app.staticTexts["Best lifts"].exists)
    XCTAssertTrue(app.tabBars.buttons["Home"].exists)
    snap("gym-flow-01-home")
    tab("History")
    snap("gym-flow-02-history")
    app.segmentedControls["history.mode"].buttons["Progress"].tap()
    XCTAssertTrue(app.staticTexts["Best lifts"].exists)
    snap("gym-flow-03-progress")
    tab("Splits")
    XCTAssertTrue(app.buttons["split.add"].exists)
    snap("gym-flow-04-splits")
    tab("Home")
    tap("home.start")
    tap("exercise.curl")
    tap("set.start")
    fill("set.reps", "8")
    tab("History")
    snap("gym-flow-05-browse-while-active")
    tap("history.resume")
    XCTAssertEqual(app.textFields["set.reps"].value as? String, "8")
    tap("set.change")
    tap("exercise.hammer")
    XCTAssertTrue(app.buttons["switch.cancel"].waitForExistence(timeout: 5))
    snap("gym-flow-06-unfinished-set-choice")
    tap("switch.cancel")
    expectExercise("Dumbbell curl")
    XCTAssertEqual(app.textFields["set.reps"].value as? String, "8")
    tap("set.change")
    tap("exercise.hammer")
    tap("switch.save")
    expectExercise("hammer")
    XCTAssertTrue(app.buttons["set.saved"].label.contains("8"))
    XCTAssertTrue(app.staticTexts["rest.elapsed"].exists)
    let initial = elapsed()
    tab("History")
    tap("history.resume")
    XCTAssertGreaterThan(elapsed(), initial)
    let beforeReload = elapsed()
    app.terminate()
    app.launchArguments = []
    app.launch()
    XCTAssertTrue(app.staticTexts["rest.elapsed"].waitForExistence(timeout: 5))
    XCTAssertGreaterThanOrEqual(elapsed(), beforeReload)
    XCTAssertTrue(app.buttons["set.change"].isHittable)
    snap("gym-flow-07-switched-with-rest-counter")
    tap("set.start")
    fill("set.reps", "7")
    tap("set.exercise")
    tap("exercise.curl")
    tap("switch.discard")
    XCTAssertTrue(app.buttons["set.start"].exists)
    XCTAssertFalse(app.staticTexts["rest.elapsed"].exists)
    expectExercise("Dumbbell curl")
    tap("session.options")
    tap("session.sets")
    XCTAssertEqual(
      app.buttons.matching(NSPredicate(format: "identifier BEGINSWITH %@", "saved.")).count, 1)
    snap("gym-flow-08-preserved-set")
    tap("records.done")
    end()
    tap("summary.done")
    tab("History")
    app.segmentedControls["history.mode"].buttons["Workouts"].tap()
    snap("gym-flow-09-finished-history")
    app.buttons.matching(NSPredicate(format: "identifier BEGINSWITH %@", "history.")).firstMatch
      .tap()
    snap("gym-flow-10-workout-detail")
  }
  func testEmptyHistoryAndSplitsNavigationAfterSkippingSetup() {
    app.terminate()
    app.launchArguments = ["--ui-reset"]
    app.launch()
    tap("onboarding.skip")
    tab("History")
    XCTAssertTrue(app.staticTexts["No workouts yet."].exists)
    snap("gym-flow-11-empty-history")
    app.segmentedControls["history.mode"].buttons["Progress"].tap()
    XCTAssertTrue(app.staticTexts["Add a split to compare its exercises."].exists)
    tab("Splits")
    tap("split.add")
    fill("split.name", "Monday")
    tap("split.exercises")
    tap("split.exercise.curl")
    tap("split.exercise.hammer")
    tap("split.exercises.done")
    tap("split.save")
    tab("Home")
    tap("home.workout")
    app.buttons["Monday"].tap()
    tap("home.start")
    tab("Splits")
    XCTAssertTrue(app.buttons["splits.resume"].exists)
    tap("splits.resume")
    XCTAssertTrue(app.buttons["set.start"].exists)
    XCTAssertFalse(app.buttons["set.start"].isEnabled)
  }

}
