import Foundation

extension Spanish {
  static let journey: [String: String] = [
    "Not recorded": "Sin registrar",
    "Your routine in numbers": "Tu rutina en cifras",
    "Training days": "Días de entrenamiento",
    "Approximate reps": "Repeticiones aproximadas",
    "A projection of your routine, not completed workouts or predicted gains.":
      "Una proyección de tu rutina, no entrenamientos completados ni ganancias previstas.",
    "scrolling breaks": "descansos con contenidos",
    "Make your next set count.": "Haz que tu próxima serie cuente.",
    "How many days a week do you work out?": "¿Cuántos días a la semana entrenas?",
    "On average, how many reps per set?": "De media, ¿cuántas repeticiones por serie?",
    "How many sets per exercise?": "¿Cuántas series por ejercicio?",
    "How many exercises on a usual training day?":
      "¿Cuántos ejercicios en un día de entrenamiento?",
    "How many minutes do you scroll between sets?":
      "¿Cuántos minutos miras contenidos entre series?",
    "Do you time your rests between sets?": "¿Mides tus descansos entre series?",
    "Do you log your workouts and look back at them?": "¿Registras y revisas tus entrenamientos?",
    "Do you record how long each set takes?": "¿Registras cuánto dura cada serie?",
    "Keep this time for yourself.": "Quédate con este tiempo.",
    "Give your next set a fair chance.": "Prepárate para tu próxima serie.",
    "Make the next workout less of a guess.": "Entrena con una referencia clara.",
    "Your next set starts here.": "Tu próxima serie empieza aquí.",
    "days / week": "días / semana",
    "exercises": "ejercicios",
    "Skip this question": "Omitir esta pregunta",
    "Your training": "Tu entrenamiento",
    "Your habits": "Tus hábitos",
    "Your next month": "Tu próximo mes",
    "Sometimes": "A veces",
    "Log and review": "Registro y reviso",
    "Log only": "Solo registro",
    "Neither": "Ninguno",
    "How many breaks do you scroll in?": "¿En cuántos descansos miras contenidos?",
    "Keep your rest visible with your sets.": "Ve tus descansos junto a tus series.",
    "Let the rest counter start when you finish a set.":
      "El contador empieza al terminar una serie.",
    "See the gap. Start when you’re ready.": "Ve el descanso. Empieza cuando estés listo.",
    "Why rest matters": "Por qué importa descansar",
    "Remember what you did.": "Recuerda lo que hiciste.",
    "See what changed.": "Ve qué cambió.",
    "Keep the comparison close to your next set.":
      "Ten la comparación a mano para tu próxima serie.",
    "Set time stays with reps and weight.": "La duración queda junto a las repeticiones y el peso.",
    "Start and finish. Set time is recorded.": "Empieza y termina. La duración queda registrada.",
    "weeks to build a record": "semanas para crear un registro",
    "sets you could track": "series que podrías registrar",
    "Over 4 weeks at your current routine": "En 4 semanas con tu rutina actual",
    "You could have a record of every one.": "Podrías tener un registro de cada una.",
    "A clear workout. A record to build on.": "Entrena con claridad. Construye tu registro.",
    "Estimated scrolling per visit": "Uso estimado del teléfono por visita",
    "potential phone-free time": "tiempo posible sin teléfono",
    "Potential phone-free time over 4 weeks": "Tiempo posible sin teléfono en 4 semanas",
    "Rest stays. Scrolling goes.": "Conserva el descanso. Deja los contenidos.",
    "Let’s check that estimate.": "Revisemos esa estimación.",
    "You’re already keeping the space between sets.": "Ya aprovechas el espacio entre series.",
    "Start by noticing your next break.": "Empieza observando tu próximo descanso.",
    "The scrolling estimate leaves no time for your workout.":
      "La estimación no deja tiempo para entrenar.",
    "One visit a day · every break · Adjust": "Una visita al día · cada descanso · Ajustar",
    "Your break estimate · Adjust": "Tu estimación de descansos · Ajustar",
    "Over four weeks": "En cuatro semanas",
    "Your four weeks": "Tus cuatro semanas",
    "Gaps include exercise changes. Supersets may need fewer.":
      "Los intervalos incluyen cambios de ejercicio. Las superseries pueden necesitar menos.",
    "breaks": "descansos",
    "Minutes scrolling per break": "Minutos de contenidos por descanso",
    "Visits on a training day": "Visitas en un día de entrenamiento",
    "More than one": "Más de una",
    "Multiple visits need a separate time estimate. Your daily sets can still be projected.":
      "Varias visitas necesitan otra estimación de tiempo. Tus series diarias pueden proyectarse.",
    "Your estimate": "Tu estimación",
    "Rest supports your next set.": "El descanso ayuda a tu próxima serie.",
    "Too little recovery can make the next set harder to perform. There isn’t one ideal rest time for everyone.":
      "Recuperarte poco puede dificultar la próxima serie. No hay un descanso ideal para todos.",
    "Timing makes the gap visible. It doesn’t measure recovery or predict muscle gain.":
      "Medir el tiempo muestra el intervalo. No mide la recuperación ni predice ganancias musculares.",
    "Rest interval research · 2024": "Investigación sobre descansos · 2024",
    "ACSM evidence review · 2026": "Revisión de evidencia ACSM · 2026",
    "Rest stays": "Conserva el descanso",
    "Example: four weeks": "Ejemplo: cuatro semanas",
    "Four weeks at your current routine": "Cuatro semanas con tu rutina actual",
    "Example rest · 2:00": "Descanso de ejemplo · 2:00",
    "Last time": "La última vez",
    "Next time": "La próxima vez",
    "same weight": "mismo peso",
    "Example set · 35 sec": "Serie de ejemplo · 35 s",
    "+1 rep at the same weight": "+1 repetición con el mismo peso",
    "Recorded timing": "Tiempos registrados",
    "Set time (seconds)": "Duración de la serie (segundos)",
    "Gap before (seconds)": "Intervalo anterior (segundos)",
    "Elapsed Start-to-Finish time. Gaps include exercise changes and interruptions.":
      "Tiempo desde el inicio hasta el final. Los intervalos incluyen cambios e interrupciones.",
    "Set time": "Duración de la serie",
    "Gap across exercises": "Intervalo entre ejercicios",
    "Gap before": "Intervalo anterior",
    "Period": "Período",
    "All time": "Todo el historial",
    "Last four weeks": "Últimas cuatro semanas",
  ]
}

extension Spanish {
  static let reset: [String: String] = [
    "How many days a week?": "¿Cuántos días por semana?",
    "How long is a usual workout?": "¿Cuánto dura tu entrenamiento?",
    "Reps per set?": "¿Repeticiones por serie?",
    "Sets per exercise?": "¿Series por ejercicio?",
    "Exercises per workout?": "¿Ejercicios por entrenamiento?",
    "How long do you scroll per break?": "¿Cuánto tiempo miras contenidos por descanso?",
    "How many breaks include scrolling?": "¿En cuántos descansos miras contenidos?",
    "Do you time your rests?": "¿Mides tus descansos?",
    "Do you log your workouts?": "¿Registras tus entrenamientos?",
    "Do you time your sets?": "¿Mides tus series?",
    "Put the phone down.": "Deja el teléfono.",
    "Finish a set. Rest starts.": "Termina la serie. Empieza el descanso.",
    "Know what to build on.": "Conoce tu punto de partida.",
    "Only time spent scrolling.": "Solo el tiempo mirando contenidos.",
    "Estimated scrolling per workout": "Tiempo estimado con el teléfono por entrenamiento",
    "Estimate details": "Detalles de la estimación",
    "Check your answers": "Revisa tus respuestas",
    "The scrolling estimate leaves no time for your workout.": "La estimación no deja tiempo para entrenar.",
    "Edit answers": "Editar respuestas",
    "About rest": "Sobre el descanso",
    "Before": "Antes", "After": "Después",
    "+1 rep · same weight": "+1 repetición · mismo peso",
    "Go to Workout": "Ir a Entrenamiento",
    "I’m not sure": "No lo sé",
    "I do timed exercises": "Hago ejercicios por tiempo",
    "Your estimate, not measured phone use.": "Tu estimación, no una medición del teléfono.",
    "Over 4 weeks": "En 4 semanas",
    "There isn’t one ideal rest time for everyone. Timing helps you notice your own intervals.": "No hay un descanso ideal para todos. Medirlo ayuda a conocer tus intervalos.",
    "Phone down": "Teléfono boca abajo", "Phone scrolling": "Teléfono mostrando contenidos",
    "Choose workout": "Elegir entrenamiento", "Create split": "Crear rutina",
    "Units": "Unidades", "Optional": "Opcional", "Sound": "Sonido",
    "Training answers": "Respuestas de entrenamiento", "Data": "Datos",
    "This demo doesn’t block other apps.": "Esta demo no bloquea otras apps.",
    "Delete training answers": "Eliminar respuestas de entrenamiento",
    "Delete training answers?": "¿Eliminar respuestas de entrenamiento?",
    "Delete answers": "Eliminar respuestas", "Workouts and splits stay saved.": "Los entrenamientos y las rutinas siguen guardados.",
    "Days / week": "Días / semana", "Workout length": "Duración del entrenamiento",
    "Reps / set": "Repeticiones / serie", "Sets / exercise": "Series / ejercicio",
    "Exercises / workout": "Ejercicios / entrenamiento",
    "Scrolling / break": "Teléfono / descanso", "Visits / day": "Visitas / día",
    "Time rests": "Medir descansos", "Time sets": "Medir series", "Workout logging": "Registro de entrenamientos",
    "Check the entered values.": "Revisa los valores introducidos.",
    "Check this value.": "Revisa este valor.",
    "Save a group of exercises.": "Guarda un grupo de ejercicios.",
    "Return to workout": "Volver al entrenamiento", "New split": "Nueva rutina",
    "This name is already used.": "Este nombre ya está en uso.", "Add an exercise to save.": "Añade un ejercicio para guardar.",
    "New exercise": "Nuevo ejercicio", "Measure": "Medida", "Time": "Tiempo",
    "Change": "Cambiar", "dumbbell": "mancuerna",
    "Finish this set?": "¿Terminar esta serie?", "Saved sets stay.": "Las series guardadas se conservan.",
    "Finish and end": "Terminar serie y entrenamiento", "Discard set and end": "Descartar serie y terminar",
    "Keep going": "Seguir", "No reps recorded": "No hay repeticiones registradas",
    "Edit reps": "Editar repeticiones", "Record attempt": "Registrar intento", "Discard set": "Descartar serie",
    "Finish and change": "Terminar serie y cambiar", "Discard set and change": "Descartar serie y cambiar",
    "Next weight": "Siguiente peso", "Undo": "Deshacer", "Type weight": "Escribir peso", "Use picker": "Usar selector",
    "Use a weight from 0 to 500.": "Usa un peso de 0 a 500.", "Add set": "Añadir serie", "Details": "Detalles",
    "Create": "Crear", "No matches": "Sin resultados", "Recent": "Recientes", "Choose exercise": "Elegir ejercicio",
    "No sets yet": "Aún no hay series", "No workouts yet": "Aún no hay entrenamientos",
    "No workouts in this period": "No hay entrenamientos en este período",
    "Exercise progress": "Progreso por ejercicio", "Last 4 weeks": "Últimas 4 semanas",
    "Free workouts": "Entrenamientos libres", "Scope": "Ámbito", "Filter": "Filtrar",
    "No records in this scope": "No hay registros en este ámbito",
    "No matching comparison yet": "Aún no hay una comparación equivalente",
    "Same weight": "Mismo peso", "Same reps": "Mismas repeticiones", "All records": "Todos los registros",
    "How it’s counted": "Cómo se calcula",
    "Logged weight × completed reps. Bodyweight adds no estimated load; dumbbell weight uses your per-dumbbell entry.": "Peso registrado × repeticiones completadas. No se estima el peso corporal; las mancuernas usan el valor por mancuerna.",
  ]
}

extension Spanish {
  static let benefits: [String: String] = [
    "Stay focused.\nStay intentional.": "Mantén el enfoque.\nEntrena con intención.",
    "Less scrolling. More attention on your workout.": "Menos contenidos. Más atención a tu entrenamiento.",
    "Out of": "De", "possible breaks": "descansos posibles", "Workout": "Entrenamiento", "Skip questions": "Omitir preguntas", "days a week": "días por semana", "day a week": "día por semana",
    "Your workouts": "Tus entrenamientos", "How GymBlock helps": "Cómo ayuda GymBlock",
    "How many days a week do you workout?": "¿Cuántos días a la semana entrenas?",
    "How long is a usual gym visit?": "¿Cuánto dura una visita habitual al gimnasio?",
    "How many reps do you do per set, on average?": "¿Cuántas repeticiones haces por serie, de media?",
    "How many sets do you do per exercise, on average?": "¿Cuántas series haces por ejercicio, de media?",
    "How many exercises in a day?": "¿Cuántos ejercicios haces al día?",
    "Do you scroll through your phone in between sets?": "¿Miras contenidos en el teléfono entre series?",
    "Do you measure how long you rest between sets?": "¿Mides cuánto descansas entre series?",
    "Do you record your workouts and look at those records later?": "¿Registras tus entrenamientos y revisas los registros después?",
    "Do you measure how long each set takes?": "¿Mides cuánto dura cada serie?",
    "Count scrolling time only.": "Cuenta solo el tiempo mirando contenidos.",
    "Yes, every break": "Sí, en cada descanso", "I record and review them": "Los registro y los reviso",
    "I record them only": "Solo los registro", "I do not record them": "No los registro", "I use timed sets": "Hago series por tiempo",
    "Let your mind rest between sets.": "Deja descansar tu mente entre series.",
    "Scrolling can add mental fatigue.": "Mirar contenidos puede aumentar la fatiga mental.",
    "Scrolling": "Con contenidos", "No scrolling": "Sin contenidos",
    "Visual metaphor · Not a nervous-system measurement.": "Metáfora visual · No mide el sistema nervioso.",
    "“Scrolling fries your nervous system which ruins your mind muscle connection.”": "«Mirar contenidos fríe tu sistema nervioso y arruina tu conexión mente-músculo».",
    "Your proposed copy · Unverified health claim": "Texto propuesto · Afirmación de salud sin verificar",
    "min of estimated scrolling per visit": "min de contenidos estimados por visita", "Check your time estimate": "Revisar tu estimación",
    "Time your rests.": "Mide tus descansos.", "Longer rest": "Descanso largo", "Timed rest": "Descanso medido",
    "Stylized model · Not measured muscle activation.": "Modelo ilustrativo · No mide la activación muscular.",
    "See what your work adds up to.": "Ve cómo se acumula tu esfuerzo.",
    "Dumbbell curl · Example records": "Curl con mancuerna · Registros de ejemplo",
    "With a record": "Con registros", "Without a record": "Sin registros", "Unknown": "Desconocido",
    "Week 1": "Semana 1", "Week 2": "Semana 2", "Week 3": "Semana 3", "Week 4": "Semana 4", "Today": "Hoy", "Baseline": "Referencia",
    "This looks motivating.": "Esto motiva.", "You can't tell if you're doing well or not.": "No puedes saber si estás mejorando.",
    "Percentages compare weight × reps with the previous record.": "Los porcentajes comparan peso × repeticiones con el registro anterior.",
    "View subscription": "Ver suscripción", "Stay focused with GymBlock.": "Mantén el enfoque con GymBlock.",
    "Measure your set and rest time.": "Mide tus series y descansos.", "See your workout progress.": "Ve tu progreso.",
    "Focus blocking is simulated in this build.": "El bloqueo es simulado en esta versión.",
    "Subscriptions are not available in this review build.": "Las suscripciones no están disponibles en esta versión de prueba.",
    "No live purchases are configured in this review build.": "No hay compras reales configuradas en esta versión de prueba.",
    "GymBlock Monthly": "GymBlock mensual", "per month": "al mes", "Subscribe": "Suscribirse",
    "Renews monthly until cancelled.": "Se renueva cada mes hasta que la canceles.", "Restore purchases": "Restaurar compras", "Try again": "Reintentar",
    "Preview workout": "Probar entrenamiento", "Simulator preview · No payment or subscription": "Prueba del simulador · Sin pago ni suscripción",
    "Terms of Use": "Condiciones de uso", "Privacy Policy": "Política de privacidad", "Not configured": "Sin configurar"
  ]
}

extension Spanish {
  /// Onboarding V5 copy.
  static let v5: [String: String] = [
    "Stay focused.": "Mantente enfocado.",
    "Tell us about you.": "Cuéntanos sobre ti.",
    "Get a buzz when rest is up.": "Recibe un aviso al terminar el descanso.",
    "Change it anytime in Settings.": "Cámbialo cuando quieras en Ajustes.",
    "Rest’s up. Time for your next set.": "Descanso terminado. Siguiente serie.",
    "Turn on rest alerts": "Activar avisos de descanso",
    "End workout?": "¿Terminar entrenamiento?",
    "will be saved.": "se guardarán.",
    "set": "serie",
    "Gender": "Género",
    "Not set": "Sin indicar",
    "Body": "Cuerpo",
    "Rest alert": "Aviso de descanso",
    "Alert after": "Avisar tras",
    "Notifications are off for GymBlock. Turn them on in iOS Settings.": "Las notificaciones de GymBlock están desactivadas. Actívalas en Ajustes de iOS.",
    "Log out": "Cerrar sesión",
    "Delete account": "Eliminar cuenta",
    "Your account lives only on this iPhone.": "Tu cuenta solo existe en este iPhone.",
    "Log out of GymBlock?": "¿Cerrar sesión en GymBlock?",
    "Your workouts and splits stay on this iPhone.": "Tus entrenamientos y rutinas se quedan en este iPhone.",
    "Delete your account?": "¿Eliminar tu cuenta?",
    "This permanently deletes your workouts, splits, answers and settings. It can’t be undone.": "Esto elimina para siempre tus entrenamientos, rutinas, respuestas y ajustes. No se puede deshacer.",
    "now": "ahora",
    "maya.lifts liked your photo": "a maya.lifts le gustó tu foto",
    "Videos you might like": "Videos que te pueden gustar",
    "New: 10 min ab burner": "Nuevo: abdominales en 10 min",
    "You coming to the gym?": "¿Vienes al gimnasio?",
    "Apps locked while you train": "Apps bloqueadas mientras entrenas",
    "Notifications arriving.": "Llegan notificaciones.",
    "Notifications are cleared and apps are locked while you train.": "Las notificaciones desaparecen y las apps se bloquean mientras entrenas.",
    "min on your phone": "min con el teléfono",
    "every workout": "en cada entrenamiento",
    "rests": "descansos",
    "That’s %@ hours a year.": "Son %@ horas al año.",
    "workouts": "entrenamientos",
    "Each dot is one 45-min workout.": "Cada punto es un entrenamiento de 45 min.",
    "Each dot is %@ workouts of 45 min.": "Cada punto son %@ entrenamientos de 45 min.",
    "Pump": "Pump",
    "Time": "Tiempo",
    "FULL PUMP": "PUMP COMPLETO",
    "Week": "Semana",
    "Weight × reps": "Peso × reps",
    "Scroll between sets.\nNever hit the pump.": "Scroll entre series.\nNunca llegas al pump.",
    "Time your rests.\nHit the pump.": "Mide tus descansos.\nLlega al pump.",
    "Reached": "Alcanzado",
    "Never reached": "Nunca alcanzado",
    "With 1:30 rests the pump builds every set until it reaches the line.": "Con descansos de 1:30 el pump sube en cada serie hasta llegar a la línea.",
    "With long phone rests the pump drains to zero after every set and never reaches the line.": "Con descansos largos con el teléfono el pump cae a cero tras cada serie y nunca llega a la línea.",
    "Commit to focus.": "Comprométete a enfocarte.",
    "commit to focus.": "comprométete a enfocarte.",
    "Press and hold.": "Mantén pulsado.",
    "Hold to commit": "Mantén para comprometerte",
    "Committed": "Comprometido",
    "My phone stays away between sets.": "Mi teléfono se queda guardado entre series.",
    "I time every rest.": "Mido cada descanso.",
    "I log every set.": "Registro cada serie.",
    "What should we call you?": "¿Cómo te llamamos?",
    "Your name": "Tu nombre",
    "Male": "Hombre",
    "Female": "Mujer",
    "Other": "Otro",
    "Units": "Unidades",
    "Height": "Altura",
    "Weight": "Peso",
    "Stays on this phone.": "Se queda en este teléfono.",
    "Here’s your phone time.": "Este es tu tiempo con el teléfono.",
    "here’s your phone time.": "este es tu tiempo con el teléfono.",
    "on your phone, every workout": "con el teléfono, en cada entrenamiento",
    "Exercises per workout": "Ejercicios por entrenamiento",
    "Sets per exercise": "Series por ejercicio",
    "Phone time per rest": "Teléfono por descanso",
    "Workouts per week": "Entrenamientos por semana",
    "Based on your answers.": "Según tus respuestas.",
    "Stay focused,": "Mantente enfocado,",
    "Stay intentional.": "Entrena con intención.",
    "Get started": "Empezar",
    "Do you use your phone between sets?": "¿Usas el teléfono entre series?",
    "Every rest": "En cada descanso",
    "Rarely": "Casi nunca",
    "Between sets, how long are you on your phone?": "Entre series, ¿cuánto tiempo usas el teléfono?",
    "Scrolling weakens your mind-muscle connection.": "Hacer scroll debilita tu conexión mente-músculo.",
    "Put it away. Feel every rep.": "Guárdalo. Siente cada repetición.",
    "While scrolling, attention drifts to the phone and signals fade before reaching the arm.":
      "Con scroll, la atención se va al teléfono y las señales se apagan antes de llegar al brazo.",
    "With the phone away, each signal reaches the arm and it flexes.":
      "Sin el teléfono, cada señal llega al brazo y se flexiona.",
    "Illustration": "Ilustración",
    "Memory forgets your progress.": "La memoria olvida tu progreso.",
    "Your log doesn’t.": "Tu registro no.",
    "Remembered weights fade into question marks, week after week.": "Los pesos recordados se vuelven signos de interrogación, semana tras semana.",
    "Logged weeks form a rising line; today is 5 kilograms heavier than week 1.": "Las semanas registradas forman una línea ascendente; hoy son 5 kilos más que en la semana 1.",
    "Example": "Ejemplo",
    "W1": "S1", "W2": "S2", "W3": "S3", "W4": "S4", "Today": "Hoy",
    "Block what distracts you.": "Bloquea lo que te distrae.",
    "Blocking is simulated in this build.": "El bloqueo está simulado en esta versión.",
    "Turn on blocking": "Activar bloqueo",
    "Not now": "Ahora no",
    "Stay focused with GymBlock.": "Mantente enfocado con GymBlock.",
    "Blocks": "Bloquea",
    "Blocks the apps you choose": "Bloquea las apps que elijas",
    "Times every rest": "Mide cada descanso",
    "Shows your progress": "Muestra tu progreso",
    "Subscribe": "Suscribirse",
    "Phone between sets": "Teléfono entre series",
    "Minutes / rest": "Minutos / descanso",
  ]
}
