import Foundation

extension Spanish {
  static let journey: [String: String] = [
    "Not recorded": "Sin registrar",
    "Your routine in numbers": "Tu rutina en cifras",
    "Training days": "Días de entrenamiento",
    "Approximate reps": "Repeticiones aproximadas",
    "A projection of your routine, not completed workouts or predicted gains.":
      "Una proyección de tu rutina, no entrenamientos completados ni ganancias previstas.",
    "scrolling breaks": "descansos con contenidos",
    "Make your next set count.": "Haz que tu próxima serie cuente.",
    "How many days a week do you work out?": "¿Cuántos días a la semana entrenas?",
    "On average, how many reps per set?": "De media, ¿cuántas repeticiones por serie?",
    "How many sets per exercise?": "¿Cuántas series por ejercicio?",
    "How many exercises on a usual training day?":
      "¿Cuántos ejercicios en un día de entrenamiento?",
    "How many minutes do you scroll between sets?":
      "¿Cuántos minutos miras contenidos entre series?",
    "Do you time your rests between sets?": "¿Mides tus descansos entre series?",
    "Do you log your workouts and look back at them?": "¿Registras y revisas tus entrenamientos?",
    "Do you record how long each set takes?": "¿Registras cuánto dura cada serie?",
    "Keep this time for yourself.": "Quédate con este tiempo.",
    "Give your next set a fair chance.": "Prepárate para tu próxima serie.",
    "Make the next workout less of a guess.": "Entrena con una referencia clara.",
    "Your next set starts here.": "Tu próxima serie empieza aquí.",
    "days / week": "días / semana",
    "exercises": "ejercicios",
    "Skip this question": "Omitir esta pregunta",
    "Your training": "Tu entrenamiento",
    "Your habits": "Tus hábitos",
    "Your next month": "Tu próximo mes",
    "Sometimes": "A veces",
    "Log and review": "Registro y reviso",
    "Log only": "Solo registro",
    "Neither": "Ninguno",
    "How many breaks do you scroll in?": "¿En cuántos descansos miras contenidos?",
    "Keep your rest visible with your sets.": "Ve tus descansos junto a tus series.",
    "Let the rest counter start when you finish a set.":
      "El contador empieza al terminar una serie.",
    "See the gap. Start when you’re ready.": "Ve el descanso. Empieza cuando estés listo.",
    "Why rest matters": "Por qué importa descansar",
    "Remember what you did.": "Recuerda lo que hiciste.",
    "See what changed.": "Ve qué cambió.",
    "Keep the comparison close to your next set.":
      "Ten la comparación a mano para tu próxima serie.",
    "Set time stays with reps and weight.": "La duración queda junto a las repeticiones y el peso.",
    "Start and finish. Set time is recorded.": "Empieza y termina. La duración queda registrada.",
    "weeks to build a record": "semanas para crear un registro",
    "sets you could track": "series que podrías registrar",
    "Over 4 weeks at your current routine": "En 4 semanas con tu rutina actual",
    "You could have a record of every one.": "Podrías tener un registro de cada una.",
    "A clear workout. A record to build on.": "Entrena con claridad. Construye tu registro.",
    "Estimated scrolling per visit": "Uso estimado del teléfono por visita",
    "potential phone-free time": "tiempo posible sin teléfono",
    "Potential phone-free time over 4 weeks": "Tiempo posible sin teléfono en 4 semanas",
    "Rest stays. Scrolling goes.": "Conserva el descanso. Deja los contenidos.",
    "Let’s check that estimate.": "Revisemos esa estimación.",
    "You’re already keeping the space between sets.": "Ya aprovechas el espacio entre series.",
    "Start by noticing your next break.": "Empieza observando tu próximo descanso.",
    "The scrolling estimate leaves no time for your workout.":
      "La estimación no deja tiempo para entrenar.",
    "One visit a day · every break · Adjust": "Una visita al día · cada descanso · Ajustar",
    "Your break estimate · Adjust": "Tu estimación de descansos · Ajustar",
    "Over four weeks": "En cuatro semanas",
    "Your four weeks": "Tus cuatro semanas",
    "Gaps include exercise changes. Supersets may need fewer.":
      "Los intervalos incluyen cambios de ejercicio. Las superseries pueden necesitar menos.",
    "breaks": "descansos",
    "Minutes scrolling per break": "Minutos de contenidos por descanso",
    "Visits on a training day": "Visitas en un día de entrenamiento",
    "More than one": "Más de una",
    "Multiple visits need a separate time estimate. Your daily sets can still be projected.":
      "Varias visitas necesitan otra estimación de tiempo. Tus series diarias pueden proyectarse.",
    "Your estimate": "Tu estimación",
    "Rest supports your next set.": "El descanso ayuda a tu próxima serie.",
    "Too little recovery can make the next set harder to perform. There isn’t one ideal rest time for everyone.":
      "Recuperarte poco puede dificultar la próxima serie. No hay un descanso ideal para todos.",
    "Timing makes the gap visible. It doesn’t measure recovery or predict muscle gain.":
      "Medir el tiempo muestra el intervalo. No mide la recuperación ni predice ganancias musculares.",
    "Rest interval research · 2024": "Investigación sobre descansos · 2024",
    "ACSM evidence review · 2026": "Revisión de evidencia ACSM · 2026",
    "Rest stays": "Conserva el descanso",
    "Example: four weeks": "Ejemplo: cuatro semanas",
    "Four weeks at your current routine": "Cuatro semanas con tu rutina actual",
    "Example rest · 2:00": "Descanso de ejemplo · 2:00",
    "Last time": "La última vez",
    "Next time": "La próxima vez",
    "same weight": "mismo peso",
    "Example set · 35 sec": "Serie de ejemplo · 35 s",
    "+1 rep at the same weight": "+1 repetición con el mismo peso",
    "Recorded timing": "Tiempos registrados",
    "Set time (seconds)": "Duración de la serie (segundos)",
    "Gap before (seconds)": "Intervalo anterior (segundos)",
    "Elapsed Start-to-Finish time. Gaps include exercise changes and interruptions.":
      "Tiempo desde el inicio hasta el final. Los intervalos incluyen cambios e interrupciones.",
    "Set time": "Duración de la serie",
    "Gap across exercises": "Intervalo entre ejercicios",
    "Gap before": "Intervalo anterior",
    "Period": "Período",
    "All time": "Todo el historial",
    "Last four weeks": "Últimas cuatro semanas",
  ]
}

extension Spanish {
  static let reset: [String: String] = [
    "How many days a week?": "¿Cuántos días por semana?",
    "How long is a usual workout?": "¿Cuánto dura tu entrenamiento?",
    "Reps per set?": "¿Repeticiones por serie?",
    "Sets per exercise?": "¿Series por ejercicio?",
    "Exercises per workout?": "¿Ejercicios por entrenamiento?",
    "How long do you scroll per break?": "¿Cuánto tiempo miras contenidos por descanso?",
    "How many breaks include scrolling?": "¿En cuántos descansos miras contenidos?",
    "Do you time your rests?": "¿Mides tus descansos?",
    "Do you log your workouts?": "¿Registras tus entrenamientos?",
    "Do you time your sets?": "¿Mides tus series?",
    "Put the phone down.": "Deja el teléfono.",
    "Finish a set. Rest starts.": "Termina la serie. Empieza el descanso.",
    "Know what to build on.": "Conoce tu punto de partida.",
    "Only time spent scrolling.": "Solo el tiempo mirando contenidos.",
    "Estimated scrolling per workout": "Tiempo estimado con el teléfono por entrenamiento",
    "Estimate details": "Detalles de la estimación",
    "Check your answers": "Revisa tus respuestas",
    "The scrolling estimate leaves no time for your workout.": "La estimación no deja tiempo para entrenar.",
    "Edit answers": "Editar respuestas",
    "About rest": "Sobre el descanso",
    "Before": "Antes", "After": "Después",
    "+1 rep · same weight": "+1 repetición · mismo peso",
    "Go to Workout": "Ir a Entrenamiento",
    "I’m not sure": "No lo sé",
    "I do timed exercises": "Hago ejercicios por tiempo",
    "Your estimate, not measured phone use.": "Tu estimación, no una medición del teléfono.",
    "Over 4 weeks": "En 4 semanas",
    "There isn’t one ideal rest time for everyone. Timing helps you notice your own intervals.": "No hay un descanso ideal para todos. Medirlo ayuda a conocer tus intervalos.",
    "Phone down": "Teléfono boca abajo", "Phone scrolling": "Teléfono mostrando contenidos",
    "Choose workout": "Elegir entrenamiento", "Create split": "Crear rutina",
    "Units": "Unidades", "Optional": "Opcional", "Sound": "Sonido",
    "Training answers": "Respuestas de entrenamiento", "Data": "Datos",
    "This demo doesn’t block other apps.": "Esta demo no bloquea otras apps.",
    "Delete training answers": "Eliminar respuestas de entrenamiento",
    "Delete training answers?": "¿Eliminar respuestas de entrenamiento?",
    "Delete answers": "Eliminar respuestas", "Workouts and splits stay saved.": "Los entrenamientos y las rutinas siguen guardados.",
    "Days / week": "Días / semana", "Workout length": "Duración del entrenamiento",
    "Reps / set": "Repeticiones / serie", "Sets / exercise": "Series / ejercicio",
    "Exercises / workout": "Ejercicios / entrenamiento",
    "Scrolling / break": "Teléfono / descanso", "Visits / day": "Visitas / día",
    "Time rests": "Medir descansos", "Time sets": "Medir series", "Workout logging": "Registro de entrenamientos",
    "Check the entered values.": "Revisa los valores introducidos.",
    "Check this value.": "Revisa este valor.",
    "Save a group of exercises.": "Guarda un grupo de ejercicios.",
    "Return to workout": "Volver al entrenamiento", "New split": "Nueva rutina",
    "This name is already used.": "Este nombre ya está en uso.", "Add an exercise to save.": "Añade un ejercicio para guardar.",
    "New exercise": "Nuevo ejercicio", "Measure": "Medida", "Time": "Tiempo",
    "Change": "Cambiar", "dumbbell": "mancuerna",
    "Finish this set?": "¿Terminar esta serie?", "Saved sets stay.": "Las series guardadas se conservan.",
    "Finish and end": "Terminar serie y entrenamiento", "Discard set and end": "Descartar serie y terminar",
    "Keep going": "Seguir", "No reps recorded": "No hay repeticiones registradas",
    "Edit reps": "Editar repeticiones", "Record attempt": "Registrar intento", "Discard set": "Descartar serie",
    "Finish and change": "Terminar serie y cambiar", "Discard set and change": "Descartar serie y cambiar",
    "Next weight": "Siguiente peso", "Undo": "Deshacer", "Type weight": "Escribir peso", "Use picker": "Usar selector",
    "Use a weight from 0 to 500.": "Usa un peso de 0 a 500.", "Add set": "Añadir serie", "Details": "Detalles",
    "Create": "Crear", "No matches": "Sin resultados", "Recent": "Recientes", "Choose exercise": "Elegir ejercicio",
    "No sets yet": "Aún no hay series", "No workouts yet": "Aún no hay entrenamientos",
    "No workouts in this period": "No hay entrenamientos en este período",
    "Exercise progress": "Progreso por ejercicio", "Last 4 weeks": "Últimas 4 semanas",
    "Free workouts": "Entrenamientos libres", "Scope": "Ámbito", "Filter": "Filtrar",
    "No records in this scope": "No hay registros en este ámbito",
    "No matching comparison yet": "Aún no hay una comparación equivalente",
    "Same weight": "Mismo peso", "Same reps": "Mismas repeticiones", "All records": "Todos los registros",
    "How it’s counted": "Cómo se calcula",
    "Logged weight × completed reps. Bodyweight adds no estimated load; dumbbell weight uses your per-dumbbell entry.": "Peso registrado × repeticiones completadas. No se estima el peso corporal; las mancuernas usan el valor por mancuerna.",
  ]
}

extension Spanish {
  static let benefits: [String: String] = [
    "Stay focused.\nStay intentional.": "Mantén el enfoque.\nEntrena con intención.",
    "Less scrolling. More attention on your workout.": "Menos contenidos. Más atención a tu entrenamiento.",
    "Out of": "De", "possible breaks": "descansos posibles", "Workout": "Entrenamiento", "Skip questions": "Omitir preguntas", "days a week": "días por semana", "day a week": "día por semana",
    "Your workouts": "Tus entrenamientos", "How GymBlock helps": "Cómo ayuda GymBlock",
    "How many days a week do you workout?": "¿Cuántos días a la semana entrenas?",
    "How long is a usual gym visit?": "¿Cuánto dura una visita habitual al gimnasio?",
    "How many reps do you do per set, on average?": "¿Cuántas repeticiones haces por serie, de media?",
    "How many sets do you do per exercise, on average?": "¿Cuántas series haces por ejercicio, de media?",
    "How many exercises in a day?": "¿Cuántos ejercicios haces al día?",
    "Do you scroll through your phone in between sets?": "¿Miras contenidos en el teléfono entre series?",
    "Do you measure how long you rest between sets?": "¿Mides cuánto descansas entre series?",
    "Do you record your workouts and look at those records later?": "¿Registras tus entrenamientos y revisas los registros después?",
    "Do you measure how long each set takes?": "¿Mides cuánto dura cada serie?",
    "Count scrolling time only.": "Cuenta solo el tiempo mirando contenidos.",
    "Yes, every break": "Sí, en cada descanso", "I record and review them": "Los registro y los reviso",
    "I record them only": "Solo los registro", "I do not record them": "No los registro", "I use timed sets": "Hago series por tiempo",
    "Let your mind rest between sets.": "Deja descansar tu mente entre series.",
    "Scrolling can add mental fatigue.": "Mirar contenidos puede aumentar la fatiga mental.",
    "Scrolling": "Con contenidos", "No scrolling": "Sin contenidos",
    "Visual metaphor · Not a nervous-system measurement.": "Metáfora visual · No mide el sistema nervioso.",
    "“Scrolling fries your nervous system which ruins your mind muscle connection.”": "«Mirar contenidos fríe tu sistema nervioso y arruina tu conexión mente-músculo».",
    "Your proposed copy · Unverified health claim": "Texto propuesto · Afirmación de salud sin verificar",
    "min of estimated scrolling per visit": "min de contenidos estimados por visita", "Check your time estimate": "Revisar tu estimación",
    "Time your rests.": "Mide tus descansos.", "Longer rest": "Descanso largo", "Timed rest": "Descanso medido",
    "Stylized model · Not measured muscle activation.": "Modelo ilustrativo · No mide la activación muscular.",
    "See what your work adds up to.": "Ve cómo se acumula tu esfuerzo.",
    "Dumbbell curl · Example records": "Curl con mancuerna · Registros de ejemplo",
    "With a record": "Con registros", "Without a record": "Sin registros", "Unknown": "Desconocido",
    "Week 1": "Semana 1", "Week 2": "Semana 2", "Week 3": "Semana 3", "Week 4": "Semana 4", "Today": "Hoy", "Baseline": "Referencia",
    "This looks motivating.": "Esto motiva.", "You can't tell if you're doing well or not.": "No puedes saber si estás mejorando.",
    "Percentages compare weight × reps with the previous record.": "Los porcentajes comparan peso × repeticiones con el registro anterior.",
    "View subscription": "Ver suscripción", "Stay focused with GymBlock.": "Mantén el enfoque con GymBlock.",
    "Measure your set and rest time.": "Mide tus series y descansos.", "See your workout progress.": "Ve tu progreso.",
    "Focus blocking is simulated in this build.": "El bloqueo es simulado en esta versión.",
    "Subscriptions aren’t switched on in this build yet.": "Las suscripciones no están disponibles en esta versión de prueba.",
    "Purchases aren’t switched on in this build yet.": "No hay compras reales configuradas en esta versión de prueba.",
    "GymBlock Monthly": "GymBlock mensual", "per month": "al mes", "Subscribe": "Suscribirse",
    "Renews monthly until cancelled.": "Se renueva cada mes hasta que la canceles.", "Restore purchases": "Restaurar compras", "Try again": "Reintentar",
    "Preview workout": "Probar entrenamiento", "Simulator preview · No payment or subscription": "Prueba del simulador · Sin pago ni suscripción",
    "Terms of Use": "Condiciones de uso", "Privacy Policy": "Política de privacidad", "Not configured": "Sin configurar"
  ]
}

extension Spanish {
  /// Onboarding V5 copy.
  static let v5: [String: String] = [
    "Stay focused.": "Mantente enfocado.",
    "min training": "min entrenando",
    "Training": "Entrenando",
    "On your phone": "Con el teléfono",
    "Based on 5 workouts a week.": "Con 5 entrenamientos por semana.",
    "A typical workout: 6 exercises × 3 sets, 2-min rests.": "Un entrenamiento típico: 6 ejercicios × 3 series, descansos de 2 min.",
    "How much do you weigh?": "¿Cuánto pesas?",
    "How tall are you?": "¿Cuánto mides?",
    "What’s your gender?": "¿Cuál es tu género?",
    "Get a buzz when rest is up.": "Recibe un aviso al terminar el descanso.",
    "Change it anytime in Settings.": "Cámbialo cuando quieras en Ajustes.",
    "Rest’s up. Time for your next set.": "Descanso terminado. Siguiente serie.",
    "Turn on rest alerts": "Activar avisos de descanso",
    "End workout?": "¿Terminar entrenamiento?",
    "will be saved.": "se guardarán.",
    "set": "serie",
    "Gender": "Género",
    "Not set": "Sin indicar",
    "Body": "Cuerpo",
    "Rest alert": "Aviso de descanso",
    "Alert after": "Avisar tras",
    "Notifications are off for GymBlock. Turn them on in iOS Settings.": "Las notificaciones de GymBlock están desactivadas. Actívalas en Ajustes de iOS.",
    "Log out": "Cerrar sesión",
    "Delete account": "Eliminar cuenta",
    "Your account lives only on this iPhone.": "Tu cuenta solo existe en este iPhone.",
    "Log out of GymBlock?": "¿Cerrar sesión en GymBlock?",
    "Your workouts and splits stay on this iPhone.": "Tus entrenamientos y rutinas se quedan en este iPhone.",
    "Delete your account?": "¿Eliminar tu cuenta?",
    "This permanently deletes your workouts, splits, answers and settings. It can’t be undone.": "Esto elimina para siempre tus entrenamientos, rutinas, respuestas y ajustes. No se puede deshacer.",
    "now": "ahora",
    "maya.lifts liked your photo": "a maya.lifts le gustó tu foto",
    "Videos you might like": "Videos que te pueden gustar",
    "New: 10 min ab burner": "Nuevo: abdominales en 10 min",
    "You coming to the gym?": "¿Vienes al gimnasio?",
    "Apps locked while you train": "Apps bloqueadas mientras entrenas",
    "Notifications arriving.": "Llegan notificaciones.",
    "Notifications are cleared and apps are locked while you train.": "Las notificaciones desaparecen y las apps se bloquean mientras entrenas.",
    "min on your phone": "min con el teléfono",
    "every workout": "en cada entrenamiento",
    "rests": "descansos",
    "That’s %@ hours a year.": "Son %@ horas al año.",
    "workouts": "entrenamientos",
    "Each dot is one 45-min workout.": "Cada punto es un entrenamiento de 45 min.",
    "Each dot is %@ workouts of 45 min.": "Cada punto son %@ entrenamientos de 45 min.",
    "Pump": "Pump",
    "Time": "Tiempo",
    "FULL PUMP": "PUMP COMPLETO",
    "Week": "Semana",
    "Weight × reps": "Peso × reps",
    "Scroll between sets.\nNever hit the pump.": "Scroll entre series.\nNunca llegas al pump.",
    "Time your rests.\nHit the pump.": "Mide tus descansos.\nLlega al pump.",
    "Reached": "Alcanzado",
    "Never reached": "Nunca alcanzado",
    "With 1:30 rests the pump builds every set until it reaches the line.": "Con descansos de 1:30 el pump sube en cada serie hasta llegar a la línea.",
    "With long phone rests the pump drains to zero after every set and never reaches the line.": "Con descansos largos con el teléfono el pump cae a cero tras cada serie y nunca llega a la línea.",
    "Commit to focus.": "Comprométete a enfocarte.",
    "commit to focus.": "comprométete a enfocarte.",
    "Press and hold.": "Mantén pulsado.",
    "Hold to commit": "Mantén para comprometerte",
    "Committed": "Comprometido",
    "My phone stays away between sets.": "Mi teléfono se queda guardado entre series.",
    "I time every rest.": "Mido cada descanso.",
    "I log every set.": "Registro cada serie.",
    "What should we call you?": "¿Cómo te llamamos?",
    "Your name": "Tu nombre",
    "Male": "Hombre",
    "Female": "Mujer",
    "Other": "Otro",
    "Units": "Unidades",
    "Height": "Altura",
    "Weight": "Peso",
    "Stays on this phone.": "Se queda en este teléfono.",
    "Here’s how much time you spend on your phone during your workout session.": "Este es el tiempo que pasas con el teléfono durante tu entrenamiento.",
    "here’s how much time you spend on your phone during your workout session.": "este es el tiempo que pasas con el teléfono durante tu entrenamiento.",
    "on your phone, every workout": "con el teléfono, en cada entrenamiento",
    "Exercises per workout": "Ejercicios por entrenamiento",
    "Sets per exercise": "Series por ejercicio",
    "Phone time per rest": "Teléfono por descanso",
    "Workouts per week": "Entrenamientos por semana",
    "Based on your answers.": "Según tus respuestas.",
    "Stay focused,": "Mantente enfocado,",
    "Stay intentional.": "Entrena con intención.",
    "Get started": "Empezar",
    "Do you use your phone between sets?": "¿Usas el teléfono entre series?",
    "Every rest": "En cada descanso",
    "Rarely": "Casi nunca",
    "Between sets, how long are you on your phone?": "Entre series, ¿cuánto tiempo usas el teléfono?",
    "Scrolling weakens your mind-muscle connection.": "Hacer scroll debilita tu conexión mente-músculo.",
    "Put it away. Feel every rep.": "Guárdalo. Siente cada repetición.",
    "While scrolling, attention drifts to the phone and signals fade before reaching the arm.":
      "Con scroll, la atención se va al teléfono y las señales se apagan antes de llegar al brazo.",
    "With the phone away, each signal reaches the arm and it flexes.":
      "Sin el teléfono, cada señal llega al brazo y se flexiona.",
    "Illustration": "Ilustración",
    "Memory forgets your progress.": "La memoria olvida tu progreso.",
    "Your log doesn’t.": "Tu registro no.",
    "Remembered weights fade into question marks, week after week.": "Los pesos recordados se vuelven signos de interrogación, semana tras semana.",
    "Logged weeks form a rising line; today is 5 kilograms heavier than week 1.": "Las semanas registradas forman una línea ascendente; hoy son 5 kilos más que en la semana 1.",
    "Example": "Ejemplo",
    "since last PR": "desde el último récord",
    "Beat a set to earn one.": "Supera una serie para conseguir uno.",
    "time training": "tiempo entrenando",
    "days ago": "días",
    "weeks ago": "semanas",
    "Time training": "Tiempo entrenando",
    "All time": "En total",
    "Minutes per week": "Minutos por semana",
    "W1": "S1", "W2": "S2", "W3": "S3", "W4": "S4", "Today": "Hoy",
    "Block what distracts you.": "Bloquea lo que te distrae.",
    "Blocking is simulated in this build.": "El bloqueo está simulado en esta versión.",
    "Turn on blocking": "Activar bloqueo",
    "Not now": "Ahora no",
    "Stay focused with GymBlock.": "Mantente enfocado con GymBlock.",
    "Blocks": "Bloquea",
    "Blocks the apps you choose": "Bloquea las apps que elijas",
    "Times every rest": "Mide cada descanso",
    "Shows your progress": "Muestra tu progreso",
    "Subscribe": "Suscribirse",
    "Phone between sets": "Teléfono entre series",
    "Minutes / rest": "Minutos / descanso",
  ]
}

extension Spanish {
  /// The workout, Home and Summary (v6).
  static let v6: [String: String] = [
    // Redesign copy (8 Oct 2026).
    // Account, subscription and legal (8 Oct 2026).
    "Keep your progress safe.": "Guarda tu progreso.",
    "Your workouts sync to your account and come back on any iPhone.": "Tus entrenamientos se sincronizan con tu cuenta y vuelven en cualquier iPhone.",
    "Continue with Apple": "Continuar con Apple",
    "Continue with Google": "Continuar con Google",
    "I already have an account": "Ya tengo una cuenta",
    "Your account": "Tu cuenta",
    "Backed up as you train": "Copia de seguridad mientras entrenas",
    "Every set is saved to your account.": "Cada serie se guarda en tu cuenta.",
    "Same log on any iPhone": "El mismo registro en cualquier iPhone",
    "Sign in and it’s all there.": "Inicia sesión y ahí está todo.",
    "Private": "Privado",
    "Only you can read your data.": "Solo tú puedes leer tus datos.",
    "Yearly": "Anual",
    "Monthly": "Mensual",
    "Best value": "Mejor precio",
    "per year": "al año",
    "per month": "al mes",
    "month": "mes",
    "year": "año",
    "Start %@-day free trial": "Empieza %@ días gratis",
    "Auto-renews. Cancel anytime in iOS Settings.": "Se renueva automáticamente. Cancela cuando quieras en Ajustes de iOS.",
    "Terms of Use": "Términos de uso",
    "Privacy Policy": "Política de privacidad",
    "Terms of Service": "Términos del servicio",
    "Support": "Soporte",
    "Legal": "Legal",
    "Account": "Cuenta",
    "Signed in": "Sesión iniciada",
    "Sign in": "Iniciar sesión",
    "Renews": "Se renueva",
    "Expires": "Caduca",
    "Clear this iPhone": "Vaciar este iPhone",
    "Clear this iPhone?": "¿Vaciar este iPhone?",
    "Clear": "Vaciar",
    "Log out keeps your account. Delete removes it and everything synced to it.": "Cerrar sesión conserva tu cuenta. Eliminar la borra junto con todo lo sincronizado.",
    "Development run: both act on this iPhone only.": "Ejecución de desarrollo: ambos actúan solo en este iPhone.",
    "Sign in to back up your workouts and keep them on any iPhone.": "Inicia sesión para guardar tus entrenamientos y tenerlos en cualquier iPhone.",
    "Your workouts stay in your account. This iPhone is cleared.": "Tus entrenamientos siguen en tu cuenta. Este iPhone se vacía.",
    "This permanently deletes your account, workouts, splits, answers and settings everywhere. It can’t be undone.": "Elimina para siempre tu cuenta, entrenamientos, divisiones, respuestas y ajustes en todas partes. No se puede deshacer.",
    "Could not delete the account": "No se pudo eliminar la cuenta",
    "Check your connection and try again.": "Comprueba tu conexión e inténtalo de nuevo.",
    "Synced to your account.": "Sincronizado con tu cuenta.",
    "Push, Pull, Legs…": "Empuje, Tirón, Pierna…",
    "Add more": "Añadir más",
    "Add the exercises in the order you do them. You can drag them later.": "Añade los ejercicios en el orden en que los haces. Luego puedes arrastrarlos.",
    "Drag to reorder. Swipe left to remove.": "Arrastra para reordenar. Desliza a la izquierda para quitar.",
    "Add “%@”": "Añadir “%@”",
    "selected": "seleccionados",
    "Progress": "Progreso",
    "week streak": "semanas de racha",
    "Train this week to keep it.": "Entrena esta semana para mantenerla.",
    "One workout starts it.": "Un entrenamiento la empieza.",
    "workouts": "entrenamientos",
    "PRs · 4 wks": "Récords · 4 sem",
    "lifted": "levantados",
    "Example until your first workout": "Ejemplo hasta tu primer entrenamiento",
    "Example": "Ejemplo",
    "since last PR": "desde el último récord",
    "Beat a set to earn one.": "Supera una serie para conseguir uno.",
    "time training": "tiempo entrenando",
    "days ago": "días",
    "weeks ago": "semanas",
    "Time training": "Tiempo entrenando",
    "All time": "En total",
    "Minutes per week": "Minutos por semana",
    "at": "a",
    "rests on time": "descansos a tiempo",
    "this week": "esta semana",
    "Your first workout lights the first square.": "Tu primer entrenamiento enciende el primer cuadro.",
    "1 workout in 12 weeks": "1 entrenamiento en 12 semanas",
    "%d workouts in 12 weeks": "%d entrenamientos en 12 semanas",
    "Rests on time": "Descansos a tiempo",
    "Lifts up": "Levantamientos mejorados",
    "Measured once you log timed rests.": "Se mide cuando registres descansos cronometrados.",
    "avg": "media",
    "target": "objetivo",
    "Like-for-like gains, last 4 weeks.": "Mejoras comparables, últimas 4 semanas.",
    "exercise beaten like for like, 4 weeks": "ejercicio superado de forma comparable, 4 semanas",
    "exercises beaten like for like, 4 weeks": "ejercicios superados de forma comparable, 4 semanas",
    "Starts this workout": "Empieza este entrenamiento",
    "1-week streak": "Racha de 1 semana",
    "%d-week streak": "Racha de %d semanas",
    "Weight moved per week": "Peso movido por semana",
    "Reps per week": "Repeticiones por semana",
    "Train next week too and the line begins.": "Entrena también la semana que viene y empieza la línea.",
    "vs last month": "frente al mes pasado",
    "this week so far": "esta semana hasta ahora",
    "Your first workouts draw the line here.": "Tus primeros entrenamientos dibujan la línea aquí.",
    "trained": "entrenado",
    "Chest & shoulders": "Pecho y hombros",
    "Set up your splits.": "Configura tus rutinas.",
    "Optional. You can always train freely and add splits later.": "Opcional. Siempre puedes entrenar libremente y añadir rutinas después.",
    "Home lines up the next split and its last weights.": "Inicio prepara la siguiente rutina con sus últimos pesos.",
    "A split is a workout you repeat: Push, Pull, Legs. Name one, add its exercises, and each workout starts with last time’s weights ready.": "Una rutina es un entrenamiento que repites: Empuje, Tirón, Pierna. Ponle nombre, añade sus ejercicios y cada entrenamiento empieza con los pesos de la última vez.",
    "Add your first split": "Añade tu primera rutina",
    "Add another split": "Añade otra rutina",
    "Start training": "Empezar a entrenar",
    "Skip for now": "Saltar por ahora",
    "You can add it again any time.": "Puedes añadirla de nuevo cuando quieras.",
    "Good morning": "Buenos días",
    "Good afternoon": "Buenas tardes",
    "Good evening": "Buenas noches",
    "Pick exercises as you go. Your last weight and reps load for each one.": "Elige ejercicios sobre la marcha. Tu último peso y repeticiones se cargan en cada uno.",
    "blocked while you train · preview": "bloqueadas mientras entrenas · vista previa",
    "How it works": "Cómo funciona",
    "Start set, lift, Finish set.": "Empezar serie, levantar, Terminar serie.",
    "Your weight and reps are remembered for next time.": "Tu peso y repeticiones se recuerdan para la próxima vez.",
    "Put the phone down.": "Deja el teléfono.",
    "The rest counts on the Lock Screen and buzzes when it’s up.": "El descanso cuenta en la pantalla bloqueada y vibra al terminar.",
    "See what you beat.": "Mira lo que superaste.",
    "Every like-for-like gain shows up after the workout.": "Cada mejora comparable aparece al terminar.",
    "First time": "Primera vez",
    "Last gain": "Última mejora",
    "Stronger than last time": "Más fuerte que la última vez",
    "First one in the log": "La primera en el registro",
    "Avg rest": "Descanso medio",
    "1 exercise": "1 ejercicio",
    "exercises": "ejercicios",
    "Exercises": "Ejercicios",
    "Paused · clocks stopped · apps unblocked (preview)": "En pausa · relojes parados · apps desbloqueadas (vista previa)",
    "Paused · every clock is stopped": "En pausa · todos los relojes parados",
    "Phone away. Rests timed. Progress kept.": "Teléfono fuera. Descansos cronometrados. Progreso guardado.",
    "Stays on this iPhone. Never shared.": "Se queda en este iPhone. Nunca se comparte.",
    "One buzz when your rest is up. Change it anytime.": "Una vibración cuando acaba tu descanso. Cámbialo cuando quieras.",
    "A typical workout: 6 exercises × 3 sets, 2-minute rests.": "Un entrenamiento típico: 6 ejercicios × 3 series, descansos de 2 minutos.",
    "At 5 workouts a week. Your own numbers, multiplied out.": "Con 5 entrenamientos por semana. Tus propios números, multiplicados.",
    "Hold the button until it fills.": "Mantén el botón hasta que se llene.",
    "Illustrative, not a measurement.": "Ilustrativo, no una medición.",
    "An example log, not your data.": "Un registro de ejemplo, no tus datos.",
    "Blocking is a preview in this build: nothing is enforced yet.": "El bloqueo es una vista previa en esta versión: aún no se aplica nada.",
    "How long on your phone, each rest?": "¿Cuánto tiempo con el teléfono en cada descanso?",
    "Choose at least one app.": "Elige al menos una app.",
    "%@ blocked from Start to Finish.": "%@ bloqueadas de Empezar a Terminar.",
    "1 app": "1 app",
    "apps": "apps",
    "Membership": "Suscripción",
    "From Start workout to Finish.": "De Empezar entrenamiento a Terminar.",
    "A buzz on the Lock Screen when it’s up.": "Una vibración en la pantalla bloqueada cuando acaba.",
    "Keeps your progress": "Guarda tu progreso",
    "Every set logged, every gain shown.": "Cada serie registrada, cada mejora visible.",
    "Cancel anytime": "Cancela cuando quieras",
    "Subscriptions aren’t switched on in this build yet.": "Las suscripciones aún no están activadas en esta versión.",
    "Purchases aren’t switched on in this build yet.": "Las compras aún no están activadas en esta versión.",
    "There's no server account yet. Both act on this iPhone only.": "Aún no hay cuenta en un servidor. Ambas acciones afectan solo a este iPhone.",
    "Add a weight": "Añade un peso",
    "Add the weight for this set.": "Añade el peso de esta serie.",
    "Apps": "Apps",
    "BW": "PC",
    "Barbell curl": "Curl con barra",
    "Barbell row": "Remo con barra",
    "Cable triceps pushdown": "Extensión de tríceps en polea",
    "Calf raise": "Elevación de gemelos",
    "Chest fly": "Aperturas de pecho",
    "Dip": "Fondos",
    "Hanging leg raise": "Elevación de piernas colgado",
    "Hip thrust": "Hip thrust",
    "Incline bench press": "Press inclinado",
    "Leg curl": "Curl femoral",
    "Leg extension": "Extensión de cuádriceps",
    "Leg press": "Prensa de piernas",
    "Plank": "Plancha",
    "Pull-up": "Dominadas",
    "Push-up": "Flexiones",
    "Romanian deadlift": "Peso muerto rumano",
    "Rowing machine": "Remo ergómetro",
    "Seated cable row": "Remo sentado en polea",
    "Better than last time": "Mejor que la última vez",
    "Block apps during workouts": "Bloquear apps al entrenar",
    "Blocking": "Bloqueo",
    "Choose another workout": "Elegir otro entrenamiento",
    "Delete split": "Eliminar rutina",
    "Delete this split?": "¿Eliminar esta rutina?",
    "Delete this workout?": "¿Eliminar este entrenamiento?",
    "Delete workout": "Eliminar entrenamiento",
    "Discard set and switch": "Descartar serie y cambiar",
    "Edit last set": "Editar última serie",
    "End": "Terminar",
    "Finish this set first?": "¿Terminar antes esta serie?",
    "Finish workout": "Terminar entrenamiento",
    "Finished workouts appear here.": "Aquí aparecen los entrenamientos terminados.",
    "Finishing ends it then.": "Al terminarlo, acaba a esa hora.",
    "Its sets leave History and progress. This can’t be undone.": "Sus series salen del historial y del progreso. No se puede deshacer.",
    "Last activity at": "Última actividad a las",
    "Less": "Menos",
    "My split": "Mi rutina",
    "Next exercise": "Siguiente ejercicio",
    "Nice work,": "Buen trabajo,",
    "One tap logs a set. Rest still counts.": "Un toque registra la serie. El descanso se sigue contando.",
    "Opens History": "Abre el historial",
    "Past workouts stay in History.": "Los entrenamientos pasados siguen en el historial.",
    "Pick an exercise": "Elige un ejercicio",
    "Pick exercises as you go.": "Elige ejercicios sobre la marcha.",
    "Rest length": "Duración del descanso",
    "Rest’s up": "Descanso terminado",
    "Sample data": "Datos de ejemplo",
    "Saved as a split.": "Guardado como rutina.",
    "Set 1": "Serie 1",
    "Start and Finish each set to time it.": "Inicia y termina cada serie para medirla.",
    "Start it from Home next time.": "La próxima vez, iníciala desde Inicio.",
    "Still working out?": "¿Sigues entrenando?",
    "Tap Finish when you stop.": "Toca Terminar serie al parar.",
    "The clock times this exercise.": "El reloj mide este ejercicio.",
    "The unfinished set won’t be saved.": "La serie sin terminar no se guardará.",
    "Time each set": "Medir cada serie",
    "Timed": "Por tiempo",
    "Up next": "Siguiente",
    "Workout saved.": "Entrenamiento guardado.",
    "Workout time": "Tiempo de entrenamiento",
    "You": "Tú",
    "blocking simulated": "bloqueo simulado",
    "bodyweight": "peso corporal",
    "done": "hechas",
    "each": "cada una",
    "more": "más",
    "of": "de",
    "today": "hoy",
    "total": "total",
    "weight": "peso",
    "yesterday": "ayer",
    "Average rest": "Descanso medio",
    "Your exercises": "Tus ejercicios",
    "Undo delete": "Deshacer",
    "Pause workout": "Pausar entrenamiento",
    "Resume workout": "Reanudar entrenamiento",
    "Resume": "Reanudar",
    "Paused": "En pausa",
    "Paused at": "En pausa desde las",
    "Finishing ends it at your last set.": "Al terminarlo, acaba en tu última serie.",
    "Paused · clocks stopped": "En pausa · relojes detenidos",
    "Paused · clocks stopped · blocking lifted (simulated)": "En pausa · relojes detenidos · bloqueo quitado (simulado)",
    // Real blocking through Screen Time.
    "Uses Apple’s Screen Time. Pausing your workout lifts it.": "Usa Tiempo de uso de Apple. Pausar el entrenamiento lo quita.",
    "Choose apps": "Elegir apps",
    "Choose": "Elegir",
    "Screen Time access is off. Allow it in iOS Settings, or choose Not now.": "El acceso a Tiempo de uso está desactivado. Permítelo en Ajustes de iOS o elige Ahora no.",
    "Choose what to block from Start workout to Finish.": "Elige qué bloquear desde Empezar hasta Terminar.",
    "Choose the apps that pull you in.": "Elige las apps que te atrapan.",
    "1 category": "1 categoría", "categories": "categorías", "1 site": "1 web", "sites": "webs",
    "blocked while you train": "bloqueadas mientras entrenas",
    "Choose apps to block in Settings": "Elige qué apps bloquear en Ajustes",
    "Paused · clocks stopped · apps unblocked": "En pausa · relojes parados · apps desbloqueadas",
    "Apps to block": "Apps que bloquear",
    "Screen Time access is off for GymBlock. Allow it in iOS Settings.": "El acceso de GymBlock a Tiempo de uso está desactivado. Permítelo en Ajustes de iOS.",
    "Uses Apple’s Screen Time from Start workout to Finish. Pausing lifts it.": "Usa Tiempo de uso de Apple desde Empezar hasta Terminar. Pausar lo quita.",
  ]
}
