import Foundation

extension Spanish {
  static let journey: [String: String] = [
    "Not recorded": "Sin registrar",
    "Your routine in numbers": "Tu rutina en cifras",
    "Training days": "Días de entrenamiento",
    "Approximate reps": "Repeticiones aproximadas",
    "A projection of your routine, not completed workouts or predicted gains.":
      "Una proyección de tu rutina, no entrenamientos completados ni ganancias previstas.",
    "scrolling breaks": "descansos con contenidos",
    "Make your next set count.": "Haz que tu próxima serie cuente.",
    "How many days a week do you work out?": "¿Cuántos días a la semana entrenas?",
    "On average, how many reps per set?": "De media, ¿cuántas repeticiones por serie?",
    "How many sets per exercise?": "¿Cuántas series por ejercicio?",
    "How many exercises on a usual training day?":
      "¿Cuántos ejercicios en un día de entrenamiento?",
    "How many minutes do you scroll between sets?":
      "¿Cuántos minutos miras contenidos entre series?",
    "Do you time your rests between sets?": "¿Mides tus descansos entre series?",
    "Do you log your workouts and look back at them?": "¿Registras y revisas tus entrenamientos?",
    "Do you record how long each set takes?": "¿Registras cuánto dura cada serie?",
    "Keep this time for yourself.": "Quédate con este tiempo.",
    "Give your next set a fair chance.": "Prepárate para tu próxima serie.",
    "Make the next workout less of a guess.": "Entrena con una referencia clara.",
    "Your next set starts here.": "Tu próxima serie empieza aquí.",
    "days / week": "días / semana",
    "exercises": "ejercicios",
    "Skip this question": "Omitir esta pregunta",
    "Your training": "Tu entrenamiento",
    "Your habits": "Tus hábitos",
    "Your next month": "Tu próximo mes",
    "Sometimes": "A veces",
    "Log and review": "Registro y reviso",
    "Log only": "Solo registro",
    "Neither": "Ninguno",
    "How many breaks do you scroll in?": "¿En cuántos descansos miras contenidos?",
    "Keep your rest visible with your sets.": "Ve tus descansos junto a tus series.",
    "Let the rest counter start when you finish a set.":
      "El contador empieza al terminar una serie.",
    "See the gap. Start when you’re ready.": "Ve el descanso. Empieza cuando estés listo.",
    "Why rest matters": "Por qué importa descansar",
    "Remember what you did.": "Recuerda lo que hiciste.",
    "See what changed.": "Ve qué cambió.",
    "Keep the comparison close to your next set.":
      "Ten la comparación a mano para tu próxima serie.",
    "Set time stays with reps and weight.": "La duración queda junto a las repeticiones y el peso.",
    "Start and finish. Set time is recorded.": "Empieza y termina. La duración queda registrada.",
    "weeks to build a record": "semanas para crear un registro",
    "sets you could track": "series que podrías registrar",
    "Over 4 weeks at your current routine": "En 4 semanas con tu rutina actual",
    "You could have a record of every one.": "Podrías tener un registro de cada una.",
    "A clear workout. A record to build on.": "Entrena con claridad. Construye tu registro.",
    "Estimated scrolling per visit": "Uso estimado del teléfono por visita",
    "potential phone-free time": "tiempo posible sin teléfono",
    "Potential phone-free time over 4 weeks": "Tiempo posible sin teléfono en 4 semanas",
    "Rest stays. Scrolling goes.": "Conserva el descanso. Deja los contenidos.",
    "Let’s check that estimate.": "Revisemos esa estimación.",
    "You’re already keeping the space between sets.": "Ya aprovechas el espacio entre series.",
    "Start by noticing your next break.": "Empieza observando tu próximo descanso.",
    "The scrolling estimate leaves no time for your workout.":
      "La estimación no deja tiempo para entrenar.",
    "One visit a day · every break · Adjust": "Una visita al día · cada descanso · Ajustar",
    "Your break estimate · Adjust": "Tu estimación de descansos · Ajustar",
    "Over four weeks": "En cuatro semanas",
    "Your four weeks": "Tus cuatro semanas",
    "Gaps include exercise changes. Supersets may need fewer.":
      "Los intervalos incluyen cambios de ejercicio. Las superseries pueden necesitar menos.",
    "breaks": "descansos",
    "Minutes scrolling per break": "Minutos de contenidos por descanso",
    "Visits on a training day": "Visitas en un día de entrenamiento",
    "More than one": "Más de una",
    "Multiple visits need a separate time estimate. Your daily sets can still be projected.":
      "Varias visitas necesitan otra estimación de tiempo. Tus series diarias pueden proyectarse.",
    "Your estimate": "Tu estimación",
    "Rest supports your next set.": "El descanso ayuda a tu próxima serie.",
    "Too little recovery can make the next set harder to perform. There isn’t one ideal rest time for everyone.":
      "Recuperarte poco puede dificultar la próxima serie. No hay un descanso ideal para todos.",
    "Timing makes the gap visible. It doesn’t measure recovery or predict muscle gain.":
      "Medir el tiempo muestra el intervalo. No mide la recuperación ni predice ganancias musculares.",
    "Rest interval research · 2024": "Investigación sobre descansos · 2024",
    "ACSM evidence review · 2026": "Revisión de evidencia ACSM · 2026",
    "Rest stays": "Conserva el descanso",
    "Example: four weeks": "Ejemplo: cuatro semanas",
    "Four weeks at your current routine": "Cuatro semanas con tu rutina actual",
    "Example rest · 2:00": "Descanso de ejemplo · 2:00",
    "Last time": "La última vez",
    "Next time": "La próxima vez",
    "same weight": "mismo peso",
    "Example set · 35 sec": "Serie de ejemplo · 35 s",
    "+1 rep at the same weight": "+1 repetición con el mismo peso",
    "Recorded timing": "Tiempos registrados",
    "Set time (seconds)": "Duración de la serie (segundos)",
    "Gap before (seconds)": "Intervalo anterior (segundos)",
    "Elapsed Start-to-Finish time. Gaps include exercise changes and interruptions.":
      "Tiempo desde el inicio hasta el final. Los intervalos incluyen cambios e interrupciones.",
    "Set time": "Duración de la serie",
    "Gap across exercises": "Intervalo entre ejercicios",
    "Gap before": "Intervalo anterior",
    "Period": "Período",
    "All time": "Todo el historial",
    "Last four weeks": "Últimas cuatro semanas",
  ]
}
