#!/usr/bin/env bash
# One-shot Supabase setup for GymBlock, run AFTER creating the project in the
# Supabase dashboard (so billing is your decision, not a script's).
#
#   scripts/setup-supabase.sh <project-ref>
#
# It links this repo to the project, applies the schema (RLS included),
# pushes auth config (Sign in with Apple enabled for com.sulav.gymblock),
# deploys the delete-account function, and writes the URL + anon key into
# GymBlock/Config/Config.xcconfig (gitignored), keeping any RevenueCat key.
set -euo pipefail

REF="${1:-}"
if [[ -z "$REF" ]]; then
  echo "Usage: scripts/setup-supabase.sh <project-ref>   (Dashboard → Project Settings → General)" >&2
  exit 1
fi

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

echo "→ Linking project $REF"
supabase link --project-ref "$REF"

echo "→ Applying migrations"
supabase db push

echo "→ Pushing auth config (Apple provider)"
supabase config push --project-ref "$REF" || echo "  (config push failed — enable Apple manually: Auth → Providers → Apple, client id com.sulav.gymblock)"

echo "→ Deploying delete-account"
supabase functions deploy delete-account --project-ref "$REF"

echo "→ Writing Config.xcconfig"
ANON="$(supabase projects api-keys --project-ref "$REF" -o json | python3 -c 'import json,sys; print(next(k["api_key"] for k in json.load(sys.stdin) if k["name"]=="anon"))')"
CONFIG="GymBlock/Config/Config.xcconfig"
RC_KEY=""
if [[ -f "$CONFIG" ]]; then
  RC_KEY="$(grep -E '^REVENUECAT_API_KEY' "$CONFIG" | sed 's/^REVENUECAT_API_KEY *= *//' || true)"
fi
cat > "$CONFIG" <<CFG
// Generated by scripts/setup-supabase.sh — gitignored, never commit.
SUPABASE_URL = https:/\$()/$REF.supabase.co
SUPABASE_ANON_KEY = $ANON
REVENUECAT_API_KEY = $RC_KEY
CFG

echo "✓ Supabase ready. Rebuild the app; sign-in and friends are live."
